.\" Process this file with
.\" groff -man -Tascii ndppd.1
.\"
.TH NDPPD 1 "9/18/2011" "NDP Proxy Daemon Manual" "NDP Proxy Daemon Manual"
.SH NAME
ndppd \- NDP Proxy Daemon
.SH SYNOPSIS
.B ndppd [-d] [-vvv] [-c <config-file>] [-p <pidfile>]
.SH DESCRIPTION
.BR ndppd,
or
.BR "NDP Proxy Daemon" , 
is a daemon that proxies NDP (Neighbor Discovery Protocol) messages between interfaces.
.SH OPTIONS
.IP "-c <config-file>"
Use the alternate
.I config-file
instead of
.IR /etc/ndppd.conf .
.IP -d
Daemonizes
.B ndppd
and puts it into the background. It also
enables syslogging.
.IP "-p <pidfile>"
Creates a 
.I pidfile
at the specified location.
.IP -v
Increases logging verbosity. Can be specified several times to increase
verbosity even further.
.SH FILES
.I /etc/ndppd.conf
.RS
Default configuration file. See
.BR ndppd.conf(5)
for further details about configuration options.
.RE
.SH BUGS
No known bugs at the time of this writing.
.SH LICENSE
.EX
Copyright (C) 2011  Daniel Adolfsson <daniel@priv.nu>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.EE
.SH AUTHOR
Daniel Adolfsson <daniel@priv.nu>
.SH "SEE ALSO"
.BR ndppd.conf(5)

